<?php
/**
 * Created by PhpStorm.
 * User: weronikakrzynowek
 * Date: 19.07.18
 * Time: 12:28
 */

namespace Tc\Manufacturer\Block\Adminhtml\Manufacturer\Edit;
use Magento\Backend\Block\Widget\Tabs as WidgetTabs;

class Tabs extends WidgetTabs
{
    /**
     * Class constructor
     * @return void
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setId('manufacturer_edit_tabs');
        $this->setDestElementId('edit_form');
        $this->setTitle(__('Mannufacturer Information'));
    }

    /**
     * @return $this
     */
    protected function _beforeToHtml()
    {
        $this->addTab(
            'manufacturer_info',
            [
                'label' => __('General'),
                'title' => __('General'),
                'content' => $this->getLayout()->createBlock(
                    'Tc\Manufacturer\Block\Adminhtml\Manufacturer\Edit\Tab\Info'
                )->toHtml(),
                'active' => true
            ]
        );
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}
